name: gap_widgets_example
description: Example app for the gap_widgets package.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  gap_widgets:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
